<script setup lang="ts">
import { reactive, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import AppPage from '@/components/AppPage.vue'
import BaseButton from '@/components/BaseButton.vue'
import PagedListState from '@/components/PagedListState.vue'
import { PagedQuery } from '@/features/common/paged-query'
import { dispatchBatch, listDispatchBatches, listTasks, listVehicles } from '@/features/control/api'
import type { Batch } from '@/features/batch/model'
import { Submission } from '@/features/order/submission'
import { taskStateText, type Vehicle, type VehicleTask } from '@/features/control/model'
import { errorText } from '@/features/order/model'
import { useAccess } from '@/features/workspace/navigation'
useAccess(false, 'dispatch')
const tasks=reactive(new PagedQuery<VehicleTask>()),batches=reactive(new PagedQuery<Batch>()),vehicles=ref<Vehicle[]>([]),loadingVehicles=ref(true),vehicleError=ref(''),dispatching=ref(''),dispatchError=ref('');const dispatchSubmissions=new Map<string,Submission<{batchId:string;expectedVersion:number}>>();let sequence=0
function dispatchSubmission(batchId:string){let submission=dispatchSubmissions.get(batchId);if(!submission){submission=new Submission<{batchId:string;expectedVersion:number}>();dispatchSubmissions.set(batchId,submission)}return submission}
async function loadTasks(more=false){if(more&&(tasks.loading||tasks.loadingMore||!tasks.hasMore))return;const s=++sequence;if(more)tasks.loadingMore=true;else{tasks.reset();tasks.loading=true}try{const result=await listTasks({page:more?tasks.page+1:1,pageSize:20});if(s===sequence)(more?tasks.append(result):tasks.replace(result))}catch(e){if(s===sequence)tasks.fail(errorText(e),more)}}
async function loadVehicles(){loadingVehicles.value=true;vehicleError.value='';try{vehicles.value=(await listVehicles()).items}catch(e){vehicleError.value=errorText(e)}finally{loadingVehicles.value=false}}
async function loadBatches(){batches.reset();batches.loading=true;try{batches.replace(await listDispatchBatches({status:'READY',page:1,pageSize:20}))}catch(e){batches.fail(errorText(e))}}
async function dispatch(batch:Batch){const submission=dispatchSubmission(batch.id);if(dispatching.value||submission.busy)return;dispatching.value=batch.id;dispatchError.value='';try{const response=await submission.run({batchId:batch.id,expectedVersion:batch.version},(value,key)=>dispatchBatch(value.batchId,value.expectedVersion,key),value=>value.status==='UNKNOWN');if(response.status==='UNKNOWN'){dispatchError.value='派发结果待核对，请重试同一请求';return}if(response.status==='FAILED'){dispatchError.value=response.message||'派发请求失败，请重新发起';return}await loadBatches();uni.showToast({title:'派发请求已提交',icon:'success'})}catch(e){dispatchError.value=errorText(e)}finally{dispatching.value=''}}
function dispatchPending(id:string){return dispatchSubmission(id).pending}
function openTask(id:string){uni.navigateTo({url:`/subpackages/dispatch/task-detail?id=${encodeURIComponent(id)}`})}
function openVehicle(id:string){uni.navigateTo({url:`/subpackages/dispatch/vehicle?id=${encodeURIComponent(id)}`})}
onShow(()=>{void loadTasks();void loadVehicles();void loadBatches()})
</script>
<template><AppPage title="调度台" subtitle="车辆、任务和控制请求" :tab="0"><view class="dispatch-stack"><view class="dispatch-section"><view class="dispatch-row"><text class="dispatch-heading">待派发批次</text><BaseButton variant="plain" @click="loadBatches">刷新</BaseButton></view><text v-if="dispatchError" class="dispatch-warning">{{dispatchError}}</text><PagedListState :loading="batches.loading" :error="batches.error" :has-content="!!batches.items.length" empty-text="暂无待派发批次" @retry="loadBatches"><view v-for="batch in batches.items" :key="batch.id" class="dispatch-card"><view class="dispatch-row"><text class="dispatch-heading">{{batch.number}}</text><text class="dispatch-badge">{{batch.orderIds.length}} 单</text></view><text class="dispatch-muted">{{batch.stopName||batch.stopId}} · {{batch.vehicleId||'未绑定车辆'}}</text><BaseButton :loading="dispatching===batch.id" :disabled="!batch.vehicleId||dispatching!==''&&dispatching!==batch.id" @click="dispatch(batch)">{{dispatchPending(batch.id)?'重试同一请求':'派发任务'}}</BaseButton></view></PagedListState></view><view class="dispatch-section"><view class="dispatch-row"><text class="dispatch-heading">车辆状态</text><BaseButton variant="plain" @click="loadVehicles">刷新</BaseButton></view><StatePanel v-if="loadingVehicles" state="loading" title=""/><StatePanel v-else-if="vehicleError" state="error" title="车辆加载失败" :description="vehicleError" retry @retry="loadVehicles"/><template v-else><view v-if="!vehicles.length" class="dispatch-muted">暂无车辆</view><view v-for="vehicle in vehicles" :key="vehicle.id" class="dispatch-card" @click="openVehicle(vehicle.id)"><view class="dispatch-row"><text class="dispatch-heading">{{vehicle.name}}</text><text class="dispatch-badge">{{vehicle.online===true?'在线':vehicle.online===false?'离线':'待核对'}}</text></view><text class="dispatch-muted">{{vehicle.businessStatus||'业务状态待核对'}} · {{vehicle.taskId?'有活动任务':'暂无活动任务'}}</text><text v-if="vehicle.blockers?.length" class="dispatch-warning">{{vehicle.blockers[0].message}}</text></view></template></view><view class="dispatch-section"><text class="dispatch-heading">任务</text><PagedListState :loading="tasks.loading" :loading-more="tasks.loadingMore" :error="tasks.error" :has-content="!!tasks.items.length" :has-more="tasks.hasMore" empty-text="暂无调度任务" @retry="loadTasks()" @more="loadTasks(true)"><view v-for="task in tasks.items" :key="task.id" class="dispatch-card" @click="openTask(task.id)"><view class="dispatch-row"><text class="dispatch-heading">{{task.id}}</text><text class="dispatch-badge">{{taskStateText(task.state)}}</text></view><text class="dispatch-muted">车辆 {{task.vehicleId}} · 下一站 {{task.nextStopId||'未明确'}}</text></view></PagedListState></view></view></AppPage></template>
<style scoped>.dispatch-stack{display:flex;flex-direction:column;gap:24px}.dispatch-section{display:flex;flex-direction:column;gap:12px}.dispatch-row{display:flex;justify-content:space-between;align-items:center;gap:12px}.dispatch-heading{font-size:16px;font-weight:700}.dispatch-muted{display:block;color:#667387;font-size:13px;line-height:20px}.dispatch-warning{display:block;color:#b54708;font-size:13px;margin-top:8px}.dispatch-card{padding:16px;background:#fff;border-radius:8px}.dispatch-badge{color:#1677ff;font-size:12px}</style>
