<script setup lang="ts">
import { reactive, ref } from 'vue'
import { onLoad,onShow } from '@dcloudio/uni-app'
import BusinessPage from '@/components/BusinessPage.vue'
import BaseButton from '@/components/BaseButton.vue'
import StatePanel from '@/components/StatePanel.vue'
import { cancelTask, getDispatchBatch, getTask, goTask } from '@/features/control/api'
import { canControl, taskStateText, type VehicleTask } from '@/features/control/model'
import { controlStatusText } from '@/features/pickup/model'
import { Submission } from '@/features/order/submission'
import { errorText } from '@/features/order/model'
const id=ref(''),task=ref<VehicleTask|null>(null),batchVersion=ref<number|null>(null),loading=ref(true),error=ref(''),result=ref('')
const submission=reactive(new Submission<{action:'go'|'cancel';taskId:string;expectedVersion:number}>())
const submissionAttempt=ref<'go'|'cancel'|''>('')
async function load(){loading.value=true;error.value='';try{task.value=await getTask(id.value);batchVersion.value=(await getDispatchBatch(task.value.batchId)).version}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function control(action:'go'|'cancel'){if(!task.value||batchVersion.value===null||submission.busy)return;if(submission.pending&&submissionAttempt.value!==action){error.value='请重试上次控制操作';return}if(!submission.pending)submissionAttempt.value=action;error.value='';try{const response=await submission.run({action,taskId:task.value.id,expectedVersion:batchVersion.value},(value,key)=>value.action==='go'?goTask(value.taskId,value.expectedVersion,key):cancelTask(value.taskId,value.expectedVersion,key),value=>value.status==='UNKNOWN');result.value=controlStatusText(response.status);if(response.status==='UNKNOWN'){error.value='控制结果待核对，请重试同一请求';return}if(response.status==='FAILED'){error.value=response.message||'控制请求失败，请重新发起';return}await load()}catch(e){error.value=errorText(e)}finally{if(!submission.pending)submissionAttempt.value=''}}
onLoad(q=>{id.value=String(q?.id||'')});onShow(()=>{if(id.value)void load()})
</script>
<template><BusinessPage title="任务详情" subtitle="控制结果以服务端实际状态为准"><view class="dispatch-stack"><StatePanel v-if="loading" state="loading" title=""/><StatePanel v-else-if="error&&!task" state="error" title="加载失败" :description="error" retry @retry="load"/><template v-else-if="task"><view class="dispatch-card"><view class="dispatch-row"><text class="dispatch-heading">{{task.id}}</text><text class="dispatch-badge">{{taskStateText(task.state)}}</text></view><text class="dispatch-muted">车辆 {{task.vehicleId}} · 批次 {{task.batchId}}</text><text class="dispatch-muted">当前站 {{task.currentStopId||'未到站'}} · 下一站 {{task.nextStopId||'未明确'}}</text></view><view v-if="result" class="dispatch-card"><text class="dispatch-muted">最近控制结果：{{result}}</text></view><text v-if="error" class="dispatch-warning">{{error}}</text><text v-if="submission.pending&&!submission.busy" class="dispatch-warning">上次控制结果待核对，请重试同一请求。</text><view class="dispatch-actions"><BaseButton :disabled="submission.busy||!canControl(task,'GO')||submission.pending&&submissionAttempt!=='go'" :loading="submission.busy" @click="control('go')">{{submission.pending&&submissionAttempt==='go'?'重试同一请求':'继续出发'}}</BaseButton><BaseButton variant="secondary" :disabled="submission.busy||!canControl(task,'CANCEL')||submission.pending&&submissionAttempt!=='cancel'" :loading="submission.busy" @click="control('cancel')">{{submission.pending&&submissionAttempt==='cancel'?'重试同一请求':'取消任务'}}</BaseButton><BaseButton variant="plain" :disabled="submission.pending||submission.busy" @click="load">刷新状态</BaseButton></view></template></view></BusinessPage></template>
<style scoped>.dispatch-stack{display:flex;flex-direction:column;gap:16px}.dispatch-card{padding:16px;background:#fff;border-radius:8px}.dispatch-row{display:flex;justify-content:space-between;gap:12px}.dispatch-heading{font-size:16px;font-weight:700}.dispatch-badge{color:#1677ff;font-size:12px}.dispatch-muted{display:block;color:#667387;font-size:13px;line-height:22px;margin-top:8px}.dispatch-warning{display:block;color:#b54708}.dispatch-actions{display:flex;flex-direction:column;gap:8px}</style>
